### ISSUE TITLE
Single export format -> skip "choose export format" page

### ISSUE THREAD

**Issue by im-n1** [django-import-export/django-import-export#1312]
This is a improvement request.

Once I define in my admin class a `formats` field with a single format it doesn't make sense to ask user which format he wants to export data to. The page then contains a selectbox with only option so no need to ask user if there is no choice.

**Comment by pokken-magic** [comment]
Believe this was fixed in a recent pr for 3.x. Don’t expect we will back port. 

https://github.com/django-import-export/django-import-export/pull/1389

**Comment by trixn86** [comment]
I believe the issue creator talked about an option for skipping the form page all together and start the export immediately which is also an option I was searching for. So this was not fixed with #1389 although this was an improvement so the user doesn't first have to select the only available option. But it makes not much sense to show a form that has only one possible choice to begin with.

**Comment by matthewhegarty** [comment]
FWIW we had a [PR](https://github.com/django-import-export/django-import-export/pull/1319/files) which skipped the confirmation screen during import, but it was never finished.

**Comment by mrazzari** [comment]
@trixn86 @im-n1 here's a workaround to skip the "choose export format" page:

```python
from import_export.admin import ImportExportModelAdmin
from import_export.formats.base_formats import CSV

class BookAdmin(ImportExportModelAdmin):

    formats = [CSV]

    def export_action(self, request, *args, **kwargs):
        post = request.POST.copy() # Makes POST mutable
        post['file_format'] = '0' 
        request.POST = post 
        return super(BookAdmin, self).export_action(request, *args,**kwargs)
```
Preserves the existing logic in `ExportMixin.export_action` while improving UX.
