### ISSUE TITLE
I got error when import module: ImportError: No module named 'import_export'

### ISSUE THREAD

**Issue by AnhTranHong** [django-import-export/django-import-export#648]
although I installed django-import-export

**Comment by rapkyt** [comment]
[Duplicated](https://github.com/django-import-export/django-import-export/issues/647)

**Comment by beruic** [comment]
Did you add it to `INSTALLED_APPS` in your `settings.py`?

**Comment by srugano** [comment]
I have the same issue : 

``` 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'material',
    'django_extensions',
    'rest_framework',
    'compressor',
   ......
```
with `django-import-export==0.5.1`.

**Comment by manelclos** [comment]
Can anyone provide a stack trace?

**Comment by ipfans** [comment]
I am trying django-import-export with Django 2.0.1, I got same error as ModuleNotFoundError.

```
Traceback (most recent call last):
  File "/mnt/env/aries/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/mnt/env/aries/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/mnt/env/aries/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/mnt/env/aries/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/mnt/env/aries/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/mnt/env/aries/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/mnt/env/aries/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/mnt/code/aries/aries/wsgi.py", line 17, in <module>
    application = StaticFilesHandler(get_wsgi_application())
  File "/mnt/env/aries/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/mnt/env/aries/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/mnt/env/aries/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/mnt/env/aries/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/mnt/env/aries/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'import_export'
```
virtualenv works with pipenv:

```
$ pipenv graph
...
django-import-export==0.7.0
  - diff-match-patch [required: Any, installed: 20121119]
  - django [required: >=1.5, installed: 2.0.1]
    - pytz [required: Any, installed: 2017.3]
  - tablib [required: Any, installed: 0.12.1]
    - odfpy [required: Any, installed: 1.3.6]
    - openpyxl [required: Any, installed: 2.5.0]
      - et-xmlfile [required: Any, installed: 1.0.1]
      - jdcal [required: Any, installed: 1.3]
    - pyyaml [required: Any, installed: 3.12]
    - unicodecsv [required: Any, installed: 0.14.1]
    - xlrd [required: Any, installed: 1.1.0]
    - xlwt [required: Any, installed: 1.3.0]
djangorestframework==3.7.7
...
```

**Comment by ipfans** [comment]
Oh my fault, I used a legacy virtualenv.

**Comment by matheusjardimb** [comment]
It's an issue related with django 2.0 moving reserve method (see more at https://stackoverflow.com/a/43139407/1239006)

Importing from `from django.urls import reverse` should fix it.

**Comment by SergeyMatveevA** [comment]
Problem still stay relevant, I installed django-admin-export but get error "ModuleNotFoundError: No module named 'import_export'" when I try "python manage.py migrate" on prod server. (django 2.2, CentOS 7.6).

**Comment by jusce17** [comment]
raceback (most recent call last):

File "manage.py", line 21, in <module>

main()

File "manage.py", line 17, in main

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute

django.setup()

File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup

apps.populate(settings.INSTALLED_APPS)

File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate

app_config = AppConfig.create(entry)

File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create

module = import_module(entry)

File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

File "<frozen importlib._bootstrap>", line 983, in _find_and_load

File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'import_export'

**Comment by johnpearson81** [comment]
Have the same problem now too

**Comment by andrewgy8** [comment]
Its hard to debug this without the proper information, ie versions, how you are importing it, project structure, etc.
