### ISSUE TITLE
Easy way to integrate with django-reversion?

### ISSUE THREAD

**Issue by elcolie** [django-import-export/django-import-export#660]
https://github.com/etianen/django-reversion/issues/323
#287 
#118 

All of them are acrobatic. This is 2017 by now. 
The easiest one would be `original` module has `reversion` and `proxy` has `import-export`
But as `enj` said 

> I have one admin
view that is aware of all changes (the ImportExport one - cannot revert
anything here) and another that is aware of reversion (so it allows rolling
back to those changes but misses any imports done by import-export). What
I need is a view that can do both at the same time.

Do we have a new approach on this issue?

**Comment by photonauta35** [comment]
thanks for this issue. Same problem here.

**Comment by photonauta35** [comment]
so, this problem was solved? I appreciate if some project member talks about update matter.

**Comment by andrewgy8** [comment]
Hey @photonauta35 ! Most likely this issue was not solved, but since this is a free OS project, not everything can be addressed.  And to keep things manageable, we close issues when there is no activity on them for a while.

> A comment or commit is all it takes to keep the conversation alive.

What is your proposed solution?
