### ISSUE TITLE
Model with UUID primary key: exception on export to xlsx

### ISSUE THREAD

**Issue by vmm86** [django-import-export/django-import-export#755]
I've tried to export some rows from the model containing UUID field as primary key to various supported file formats. Export to `csv`, `ods`, `tsv`, `html` seem to work fine, but other formats (`xls`, `xlsx`, `json`, `yaml`) throw some exceptions during export.

There's an exception during export to `xlsx` file:
```
2018-03-05 08:10:38 [ERROR] exception.py:exception:135  Internal Server Error: /simsim/order/order/export/
Traceback (most recent call last):
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/admin.py", line 402, in export_action
    export_data = self.get_export_data(file_format, queryset, request=request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/admin.py", line 384, in get_export_data
    export_data = file_format.export_data(data)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/formats/base_formats.py", line 109, in export_data
    return self.get_format().export_set(dataset, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/tablib/formats/_xlsx.py", line 43, in export_set
    dset_sheet(dataset, ws, freeze_panes=freeze_panes)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/tablib/formats/_xlsx.py", line 122, in dset_sheet
    cell = ws.cell('%s%s' % (col_idx, row_number))
TypeError: cell() missing 1 required positional argument: 'column'
```
Ubuntu 16.04.4 LTS
Python 3.5.2
Django 1.11.10
tablib 0.12.1
django-import-export 1.0.0

**Comment by flesser** [comment]
This seems to be an upstream bug from tablib: kennethreitz/tablib/issues/324

see also https://stackoverflow.com/a/48598168

**Comment by adamboritz** [comment]
I'm running into this issue as well with django-import-export 0.6.1

**Comment by adriadrop** [comment]
I am having same problem with all the formats. This is the gist of what I get


```
Exception Value: | __init__() missing 1 required positional argument: 'sortable_by'
-- | --
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/import_export/admin.py in get_export_queryset, line 374

```

**Comment by flesser** [comment]
@adriadrop 
That is an incompatibility issue with `django-import-export` and Django 2.1 and seems to have been fixed in https://github.com/django-import-export/django-import-export/commit/54232db4a511cc5f0b085c6bb192c3619f27e452

Until a new release with this fix is available, you can install the current version from git:
`pip install -U git+https://github.com/django-import-export/django-import-export.git`

However, the main problem still exists: Export to *.xlsx fails, regardless of UUIDField or not.

**Comment by Exanis** [comment]
This problem is still present in the latest version from pypi, with a quite simple code :

`class TodoOptions(ImportExportModelAdmin):
    list_display = ['project_id', 'survey_name']
    autocomplete_fields = ['project_id']
    list_display_links = ['survey_name']
    list_filter = ['project_id']
    search_fields = ['project_id', 'survey_name']
    resource_class = TodoResource
    formats = [XLSX, CSV]`

A fix i've found is to specify tablib version in requirements.txt to avoid using pypi's one (it is severly outdated) and use github's one instead :

`django==2.1
git+https://github.com/kennethreitz/tablib.git
django-import-export==1.2.0`
